---
- name: Asegurar locales UTF-8 (Requisito de ROS 2)
  ansible.builtin.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Instalar herramientas base iniciales
  ansible.builtin.apt:
    pkg: 
      - software-properties-common
      - curl
      - gnupg
      - git
    update_cache: yes
  register: apt_base
  until: apt_base is success
  retries: 5
  delay: 5

- name: Descargar llave GPG de ROS 2
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
    mode: '0644'

- name: Añadir repositorio oficial de ROS 2 Jazzy
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main"
    state: present
    filename: ros2

- name: Instalar ROS 2 Jazzy, herramientas y rosdep
  ansible.builtin.apt:
    pkg: 
      - ros-jazzy-desktop
      - ros-dev-tools
      - python3-rosdep
      - ros-jazzy-rmw-cyclonedds-cpp
    state: present
    update_cache: yes
  register: apt_ros
  until: apt_ros is success
  retries: 5
  delay: 10

# --- CONFIGURACIÓN PARA USUARIOS DINÁMICOS ---

- name: Configurar carga de ROS 2 para TODOS los usuarios (presentes y futuros)
  ansible.builtin.copy:
    dest: /etc/profile.d/ros2_setup.sh
    mode: '0644'
    content: |
      # Este script carga el entorno de ROS 2 Jazzy automáticamente al iniciar sesión
      if [ -f /opt/ros/jazzy/setup.bash ]; then
        source /opt/ros/jazzy/setup.bash
      fi
      # Forzar el uso de CycloneDDS para evitar problemas de red en el aula
      export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

- name: Inicializar rosdep (Gestor de dependencias)
  ansible.builtin.command: rosdep init
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
  ignore_errors: yes

- name: Actualizar caché global de rosdep
  ansible.builtin.command: rosdep update
  changed_when: false