- name: Asegurar locales UTF-8
  ansible.builtin.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Instalar dependencias de red y GPG
  ansible.builtin.apt:
    pkg: [software-properties-common, curl, gnupg, git]
    update_cache: yes

- name: Descargar llave GPG de ROS 2
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
    mode: '0644'

- name: Añadir repositorio ROS 2 Jazzy
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main"
    state: present
    filename: ros2

- name: Instalar ROS 2 Jazzy Desktop y herramientas
  ansible.builtin.apt:
    pkg: [ros-jazzy-desktop, ros-dev-tools]
    update_cache: yes
    state: present

- name: Configurar source en .bashrc para todos los usuarios reales
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.bashrc"
    line: "source /opt/ros/jazzy/setup.bash"
    create: yes
  loop: "{{ query('lines', 'ls /home') }}"
