- name: Limpiar repositorios antiguos de Webots
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  loop:
    - webots.list
    - webots.list.save

- name: Descargar llave GPG de Webots
  ansible.builtin.get_url:
    url: https://cyberbotics.com/Cyberbotics.asc
    dest: /etc/apt/keyrings/cyberbotics.asc
    mode: '0644'

- name: Desarmar llave GPG
  ansible.builtin.shell:
    cmd: gpg --dearmor < /etc/apt/keyrings/cyberbotics.asc > /etc/apt/keyrings/cyberbotics.gpg
    creates: /etc/apt/keyrings/cyberbotics.gpg

- name: Crear repositorio Webots (Nueva Estructura)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/webots.list
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/cyberbotics.gpg] https://cyberbotics.com/debian/ stable main"
    mode: '0644'

- name: Actualizar caché e instalar
  ansible.builtin.apt:
    pkg: 
      - webots
      - ros-jazzy-webots-ros2
    update_cache: yes
