---
- name: Limpiar rastros de repositorios antiguos de Webots (APT)
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  loop:
    - webots.list
    - webots.list.save
    - cyberbotics.list

- name: Eliminar llaves GPG antiguas para evitar conflictos
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/keyrings/cyberbotics.asc
    - /etc/apt/keyrings/cyberbotics.gpg

- name: Instalar Webots vía Snap (Versión recomendada para 24.04)
  community.general.snap:
    name: webots
    state: present
    classic: yes

- name: Instalar el bridge de ROS 2 para Webots
  ansible.builtin.apt:
    name: ros-jazzy-webots-ros2
    state: present
    update_cache: yes
